### ISSUE TITLE
createUserAndReturn201HttpStatus Test: actual should be newUserDTO  instead of userDto

### ISSUE THREAD

**Issue by jayeshnachnani** [vincenzo-racca/spring-test#1]
Hi, thanks for creating a reference for Integration tests

In the createUserAndReturn201HttpStatus though, we should be comparing newUserDTO (actual) v/s userDto (expected)

I can fix it by creating a pull request

**Comment by vincenzo-racca** [comment]
Hi, thank you! You are right. You can created a pull request :)
